name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GITHUB_ARTIFACTS: coverage

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Ruby version specified in `.ruby-version`
        uses: eregon/use-ruby-action@master # this will use by default the .ruby-version file in your repository

      - name: Install required apt packages
        run: |
          sudo apt-get -y install libpq-dev

      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install

      - name: Rspec tests
        run: bundle exec rspec

      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
